RUN:
    batch_size: 16
    epochs: 100
    eval_every: 2
    lr: 1e-4
    ckpt_dir: "/srv/fast1/n.lokshin/checkpoints/diffusion"
    log_folder: "tmp"
    weight_decay: 0.0
    lr_decay_step_size: 10
    lr_gamma: 0.1
DIFFUSION:
    diffusion_steps: 200
    beta_schedule: cosine
    predict_xstart: false
    rescale_learned_sigmas: false
    rescale_timesteps: false
    timestep_respacing: ''
    loss_type: mse
    model_mean_type: x_prev
    model_var_type: fixed_small
    schedule_sampler: loss-second-moment
    p2: false
    p2_gamma: 1
    p2_k: 1
MODEL:
    attention_resolutions: 16,8
    channel_mult: ''
    class_cond: true
    dropout: 0.0
    image_size: 128
    learn_sigma: false
    num_channels: 96
    num_head_channels: -1
    num_heads: 2
    num_heads_upsample: -1
    num_res_blocks: 2
    resblock_updown: false
    use_checkpoint: false
    use_fp16: false
    use_new_attention_order: true
    use_scale_shift_norm: true
    convnext: false
