RUN:
    batch_size: 16
    epochs: 10
    eval_every: 2
    lr: 1e-3
DIFFUSION:
    diffusion_steps: 200
    noise_schedule: cosine
    predict_xstart: false
    rescale_learned_sigmas: false
    rescale_timesteps: false
    timestep_respacing: ''
    use_kl: false
MODEL:
    attention_resolutions: 16,8
    channel_mult: ''
    class_cond: true
    dropout: 0.0
    image_size: 128
    learn_sigma: false
    num_channels: 192
    num_head_channels: -1
    num_heads: 4
    num_heads_upsample: -1
    num_res_blocks: 3
    resblock_updown: false
    use_checkpoint: false
    use_fp16: false
    use_new_attention_order: false
    use_scale_shift_norm: true
